version: 0.0
os: linux
files:
  - source: /
    destination: /usr/cddemo
hooks:
  BeforeInstall:
    - location: codedeploy/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/stop_server.sh
      timeout: 300
      runas: root
